#!/bin/bash
# Quick deployment script - Run this to fix the invitation system

echo "==================================================="
echo "Invitation System - Deployment Steps"
echo "==================================================="
echo ""
echo "✅ Step 1: Verify function signature in schema.sql"
grep -A 8 "create or replace function public.create_invitation" supabase/schema.sql | head -10
echo ""
echo "✅ Step 2: Check NOTIFY signal at end of schema.sql"
tail -5 supabase/schema.sql
echo ""
echo "✅ Step 3: Verify RPC call in Members.tsx"
grep -A 7 'supabase.rpc("create_invitation"' src/pages/app/Members.tsx | head -10
echo ""
echo "✅ Step 4: Build verification"
npm run build > /dev/null 2>&1 && echo "✅ Build successful" || echo "❌ Build failed"
echo ""
echo "==================================================="
echo "📋 NEXT STEPS:"
echo "==================================================="
echo ""
echo "1. Open Supabase Dashboard → SQL Editor"
echo "2. Copy the entire contents of: supabase/schema.sql"
echo "3. Paste into SQL Editor and click 'Run'"
echo "4. Wait 5-10 seconds for PostgREST cache to refresh"
echo "5. Go to API Docs and search for 'create_invitation'"
echo "6. Confirm function appears with these parameters:"
echo "   - _email (text)"
echo "   - _org_id (uuid)       ← Key: Must be _org_id, not _org"
echo "   - _role (text)"
echo "   - _invited_by (uuid)"
echo "   - _dashboard_ids (uuid[])"
echo ""
echo "7. Test in app:"
echo "   - Navigate to Members page"
echo "   - Click 'Invite member'"
echo "   - Enter email and select role"
echo "   - Click 'Send invitation'"
echo "   - You should see success toast and email sent"
echo ""
echo "==================================================="
